enum TypeField{
  TEXTFIELD="TEXTFIELD",
  TEXTAREA="TEXTAREA",
  EMAIL="EMAIL",
  NUMBER="NUMBER",
  DATE="DATE",
  TIME="TIME",
  DATETIME="DATETIME",
  SELECT="SELECT",
  MULTIPLESELECT="MULTIPLESELECT",
  COLOR="COLOR",
}

export default TypeField;
